version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerptints:
            - "my:ssh:fingerprint:placeholder"
      - checkout
      - run:
          name: copy nodes from Github Repo to Ec2 Instance...
          command: sudo scp -o https://github.com/jitendrasharmartm/HelloWord /tmp
          background: true
workflows:
  build_and_test:
    jobs:
      - build
  # node-tests:
  #   jobs:
  #     - node/tests