version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerptints:
            - "my:ssh:fingerprint:placeholder"
      - checkout
      - run:
          name: Installing nvm and node...
          command: 'sudo curl -sL https://github.com/jitendrasharmartm/HelloWord | sudo bash -'
          background: true
          # below is not working either
          # command: |
          #   ssh $SSH_USER@SSH_HOST 'sudo curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -'
      - run:
          name: Update npm
          command: |
            ssh ec2-user@13.58.105.142 'sudo mkdir -p /tmp/newfileGit'

workflows:
  build_and_test:
    jobs:
      - build
  # node-tests:
  #   jobs:
  #     - node/test