version: 2.1
parameters:
  src-repo-url:
    type: string
    default: https://github.com/jitendrasharmartm/HelloWord
executors:
    branch-name: HelloWord
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            # 1- Copy file from Git to AWS
            scp -p "https://github.com/jitendrasharmartm/HelloWord"