version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '93:b8:a6:3f:68:2f:4a:11:3b:45:06:85:a3:72:64:09'
      - run:
          name: Create file
          command: |
           ssh $SSH_USER@SSH_HOST 'echo "hi" > /tmp/newfile'